// Configuration loaded from appconfig.json (generated by CDK at deploy time)
// Falls back to environment variables for local development

interface AppConfig {
  queryApiUrl: string;
  uploadApiUrl: string;
  region: string;
  bucketName: string;
  documentTableName?: string;
  auth: {
    user_pool_id: string;
    user_pool_client_id: string;
    identity_pool_id: string;
  };
}

let cachedConfig: AppConfig | null = null;

export async function loadConfig(): Promise<AppConfig> {
  if (cachedConfig) return cachedConfig;

  try {
    // Try to load from appconfig.json (production)
    const response = await fetch('/appconfig.json');
    if (response.ok) {
      cachedConfig = await response.json();
      return cachedConfig!;
    }
  } catch {
    // Fall through to defaults
  }

  // Fallback for local development
  cachedConfig = {
    queryApiUrl: import.meta.env.VITE_API_URL || 'http://localhost:8000',
    uploadApiUrl: import.meta.env.VITE_UPLOAD_URL || import.meta.env.VITE_API_URL || 'http://localhost:8000',
    region: import.meta.env.VITE_AWS_REGION || 'us-east-1',
    bucketName: import.meta.env.VITE_DOCUMENTS_BUCKET || '',
    documentTableName: import.meta.env.VITE_DOCUMENT_TABLE || '',
    auth: {
      user_pool_id: import.meta.env.VITE_USER_POOL_ID || '',
      user_pool_client_id: import.meta.env.VITE_USER_POOL_CLIENT_ID || '',
      identity_pool_id: import.meta.env.VITE_IDENTITY_POOL_ID || '',
    },
  };

  return cachedConfig;
}

// Synchronous config for backward compatibility (use after loadConfig is called)
export const config = {
  get apiUrl() { return cachedConfig?.queryApiUrl || 'http://localhost:8000'; },
  get uploadUrl() { return cachedConfig?.uploadApiUrl || 'http://localhost:8000'; },
  get region() { return cachedConfig?.region || 'us-east-1'; },
  get documentsBucket() { return cachedConfig?.bucketName || ''; },
  get documentTableName() { return cachedConfig?.documentTableName || ''; },
  get auth() { return cachedConfig?.auth || { user_pool_id: '', user_pool_client_id: '', identity_pool_id: '' }; },
};
